
export const USER_REQUEST="USER_REQUEST"
export const USER_FAILURE="USER_FAILURE"
export const USER_SUCCESS="USER_SUCCESS"

export const PAYMENT_REQUEST="PAYMENT_REQUEST"
export const PAYMENT_SUCCESS="PAYMENT_SUCCESS"
export const PAYMENT_FAILURE="PAYMENT_FAILURE"
