
export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_ERROR="USER_LOGIN_ERROR"

export const ADMIN_LOGIN_REQUEST="ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS="ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_ERROR="ADMIN_LOGIN_ERROR"

export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS"

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';